### ISSUE TITLE
Error when installing Modules

### ISSUE THREAD

**Issue by BennoB666** [JoomlaEstateAgency/mod_jea_emphasis#2]
Hello,

i installed JEA 3.5.1 to my Joomla 3.9.24 and everything works fine. But when i try to install the modules mod_jea_emphasis, mod_jea_search, mod_jea_slider i get an error. Is version compatible with 3.9.x?

Thx for your work.

**Comment by ilhooq** [comment]
Hi,
Which version of mod_jea_emphasis you tried to install ?
